// todo: no idea if this gradle config works, i just wanted it to compile 🫠
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    withJavadocJar()
    withSourcesJar()
}

group = 'com.sudoplay.joise'
version = file("project.version").text.trim()
def isRelease = !version.contains("SNAPSHOT")

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.11'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = POM_NAME
                description = POM_DESCRIPTION
                url = POM_URL
                licenses {
                    license {
                        name = POM_LICENSE_NAME
                        url = POM_LICENSE_URL
                    }
                }
                developers {
                    developer {
                        name = POM_DEVELOPER_NAME
                        email = POM_DEVELOPER_EMAIL
                        organization = POM_DEVELOPER_ORGANIZATION
                        organizationUrl = POM_DEVELOPER_ORGANIZATION_URL
                    }
                }
                scm {
                    url = POM_SCM_URL
                    connection = POM_SCM_CONNECTION
                    developerConnection = POM_SCM_DEV_CONNECTION
                }
            }
        }
    }

    repositories {
        maven {
            url = uri(isRelease ?
                    (project.findProperty("RELEASE_REPOSITORY_URL") ?: "https://oss.sonatype.org/service/local/staging/deploy/maven2/") :
                    (project.findProperty("SNAPSHOT_REPOSITORY_URL") ?: "https://oss.sonatype.org/content/repositories/snapshots/")
            )
            credentials {
                username = project.findProperty("NEXUS_USERNAME") ?: ""
                password = project.findProperty("NEXUS_PASSWORD") ?: ""
            }
        }
    }
}

signing {
    required { isRelease }
    sign publishing.publications.mavenJava
}
